import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "learning next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav style={{padding:"20px",marginBottom:"20px",backgroundColor:"teal"}}>
        <div>
          <Link href="/">
        Home
          </Link>
          <Link href="/Posts">
          Posts
          </Link>
          <Link href="/articales">
          Articls
          </Link>
        </div>
      </nav>
        {children}</body>
    </html>
  );
}
